language: ruby
rvm:
 - 2.2
cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
branches:
  only:
   - gh-pages
   - /.*/
before_install:
 - npm i -g amphtml-validator
install:
 - bundle install
script:
 - "./build/test.sh"
 - "./build/test-amp.sh"
 - "./build/deploy-amp.sh"
notifications:
  email: true
